// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXumhK2dYxVGOlZcFe3asKxt6U-8SC-C8',
    appId: '1:928956995400:web:1c55d24e4062936b0c057d',
    messagingSenderId: '928956995400',
    projectId: 'techhouse-c8aba',
    authDomain: 'techhouse-c8aba.firebaseapp.com',
    storageBucket: 'techhouse-c8aba.appspot.com',
    measurementId: 'G-MS28K9SRPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjs9tZIRJLj5VpPT9TjvOJ9y-vpbMnKWE',
    appId: '1:928956995400:android:70ef142e578b68fa0c057d',
    messagingSenderId: '928956995400',
    projectId: 'techhouse-c8aba',
    storageBucket: 'techhouse-c8aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Pg8j_rbLG6jOyTrxVgf76jCRR4vYH-I',
    appId: '1:928956995400:ios:c0142e2e6ffc4c1d0c057d',
    messagingSenderId: '928956995400',
    projectId: 'techhouse-c8aba',
    storageBucket: 'techhouse-c8aba.appspot.com',
    iosBundleId: 'com.example.techhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Pg8j_rbLG6jOyTrxVgf76jCRR4vYH-I',
    appId: '1:928956995400:ios:c0142e2e6ffc4c1d0c057d',
    messagingSenderId: '928956995400',
    projectId: 'techhouse-c8aba',
    storageBucket: 'techhouse-c8aba.appspot.com',
    iosBundleId: 'com.example.techhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXumhK2dYxVGOlZcFe3asKxt6U-8SC-C8',
    appId: '1:928956995400:web:224f6b75fb9fe53d0c057d',
    messagingSenderId: '928956995400',
    projectId: 'techhouse-c8aba',
    authDomain: 'techhouse-c8aba.firebaseapp.com',
    storageBucket: 'techhouse-c8aba.appspot.com',
    measurementId: 'G-RV2BP6WJXS',
  );

}